### ISSUE TITLE
Allow operator control of the PAM service name against which to authenticate users

### ISSUE THREAD

**Issue by ae6rt** [bjhaid/pam_hook#13]
Allow the operator to configure the PAM *service_name* against which users are authenticated during token creation.  Assuming this name is *pamServiceName*, the proposed change would read

```
tx, err := pam.StartFunc(pamServiceName, username, func(s pam.Style, msg string) (string, error) {
```
Reference:  [pam_start(3)](https://linux.die.net/man/3/pam_start)

**Comment by ae6rt** [comment]
I'll work on this issue.

**Comment by bjhaid** [comment]
closed by:

https://github.com/bjhaid/pam_hook/pull/14/files
